### ISSUE TITLE
Mod Rename

### ISSUE THREAD

**Issue by Metacinnabar** [withertech/CheatyToolsReloaded#1]
Suggestion: Name change
I think the name is a bit misleading since there not really "cheaty" per say, i would call them overpowered. (just change displayname in build.txt)
Ideas:
Overpowered Items

**Comment by KP2048** [comment]
There are no crafting recipes so they are intended for cheating. Say you are a mod developer and you made a post moonlord boss but you don’t want to beat the vanilla game to get to your boss, this is what you would use.

**Comment by KP2048** [comment]
I think 100,000,000 attack damage is cheaty
